sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: oHEyuLGdtZ5XHhZiojTmfkC4NqrobVkO85tUn9B727SzvXXHU6PsvraNN5U/g8YVzTXSJXY2Nxe2edWh0juDlbMY/6fmO/GAA46JnW7bpac2iIifdtN5LT8tVtzZIekokg36Pd25i0sVQhau6ANvNhTbLV7Pw3b24mNbZk5lXNBpPVPzEufh32k/JoOR1D0AQTOekABuU0nYOL2aJhFcKW1y21JiNnNlom40P5uvm4F/1aGqzNmtD2e3HyE6pESTK/4puOOhRIEXMlH/l4MkiYH7m5To3w/UMvV5CqndqAVVm5FXRYYPMRQhgQE6gYAdqiv+hZWdKYU5jBys2BFXeLELoBDFW2AMDy+XWTWadsURoRir+AbXf34kbiupTLt3hBNYy0eGWZjn2tjjKYuJt2azAtGvRYqyGbR3ooaq/jfxzn53Sgp/iP0RqTbds5N2ZZq9uKgy+eu7BhH52Z+ZJkM67WBbPu0qw6/3gr8onCmCXmqvPz6CXuTfwLnrljUsnGvKZUBquh6NbJZPnwbscMawgyyzcSsH79vVYg2SMNmip0aEUe1TF+1NigRgBbOXMDfssSZmTqRpGMN+B78BNyM77whphCyCHrHyFp9SI2/7IpOnelAvz84pESzgEnOH2YiiESTBockR948jofxeLvcV33vkvOqcPK6YQqpMswk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Mystery-of-Edwin-Drood_564
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy